services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./angular-csharp-app
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
      - "4201:80"
